# Generated by Django 3.0.3 on 2020-04-13 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FindTutors', '0005_auto_20200402_1125'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='firstname',
            field=models.CharField(default=' ', max_length=100),
        ),
        migrations.AddField(
            model_name='profile',
            name='lastname',
            field=models.CharField(default=' ', max_length=100),
        ),
        migrations.AlterField(
            model_name='tuser',
            name='username',
            field=models.CharField(default='', max_length=200),
        ),
    ]
